// <auto-generated />
namespace ToDoTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _initil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_initil));
        
        string IMigrationMetadata.Id
        {
            get { return "202007242338474__initil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
